# Generated by Django 2.1.7 on 2019-03-10 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=400)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=8)),
                ('unidad_org', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('nro_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('hay_heridos', models.BooleanField()),
                ('hay_terceros', models.BooleanField()),
                ('fecha_incidente', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_nombre', models.CharField(max_length=30)),
                ('pro_cedula', models.CharField(max_length=8)),
                ('pro_vto_libreta', models.DateField(blank=True, null=True)),
                ('pro_telefono', models.CharField(max_length=9)),
                ('pro_email', models.EmailField(blank=True, max_length=35, null=True)),
                ('pro_descripción', models.TextField(max_length=500)),
                ('ter_matricula', models.CharField(blank=True, max_length=7, null=True)),
                ('ter_aseguradora', models.CharField(blank=True, max_length=30, null=True)),
                ('ter_propietario', models.BooleanField()),
                ('ter_nombre_conductor', models.CharField(blank=True, max_length=30, null=True)),
                ('ter_cedula_conductor', models.CharField(blank=True, max_length=8, null=True)),
                ('ter_telefono_conductor', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('nro_poliza', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=8)),
                ('clave', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Vehiculo'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Poliza'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Incidente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Vehiculo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Incidente'),
        ),
    ]
