# Generated by Django 2.0.13 on 2019-03-03 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.TextField(max_length=400)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=8)),
                ('unidad_org', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('nro_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('hay_heridos', models.BooleanField()),
                ('hay_terceros', models.BooleanField()),
                ('fehca_incidente', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_nombre', models.CharField(max_length=30)),
                ('pro_cedula', models.CharField(max_length=8)),
                ('pro_vto_libreta', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_telefono', models.CharField(max_length=9)),
                ('pro_email', models.EmailField(max_length=35)),
                ('pro_sexo', models.BooleanField()),
                ('pro_descripción', models.TextField(max_length=500)),
                ('ter_matricula', models.CharField(max_length=7)),
                ('ter_aseguradora', models.CharField(max_length=30)),
                ('ter_propietario', models.BooleanField()),
                ('ter_nombre_conductor', models.CharField(max_length=30)),
                ('ter_cedula_conductor', models.CharField(max_length=8)),
                ('ter_telefono_conductor', models.CharField(max_length=9)),
                ('ter_sexo', models.BooleanField()),
                ('usuario_id', models.CharField(max_length=8)),
                ('fecha_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('nro_poliza', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=8)),
                ('clave', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Vehiculo'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='poliza_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Poliza'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='incidente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Incidente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Vehiculo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='incidente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Incidente'),
        ),
    ]
