# Generated by Django 2.0.13 on 2019-03-29 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='denuncia.Estado'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='hay_heridos',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='hay_terceros',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='pro_vto_libreta',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='ter_propietario',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='denuncia.Usuario'),
        ),
    ]
