# Generated by Django 2.0.13 on 2019-03-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_auto_20190303_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='incidente_id',
            new_name='incidente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='vehiculo_id',
            new_name='vehiculo',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='incidente_id',
            new_name='incidente',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='estado_id',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='poliza_id',
            new_name='poliza',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='poliza',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='poliza',
            old_name='vehiculo_id',
            new_name='vehiculo',
        ),
    ]
