# Generated by Django 2.0.13 on 2019-03-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0004_auto_20190303_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='pro_sexo',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='ter_sexo',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='pro_vto_libreta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
